### ISSUE TITLE
EventException in PlayerQuitEvent

### ISSUE THREAD

**Issue by bog500** [zack6849/SuperLogger#6] opened 2015-12-05 06:34 UTC
This error pops most of the time when a player quits (but not always). on my server

[01:31:00] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to SuperLogger v1.7
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:348) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:871) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:314) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NoClassDefFoundError: com/zack6849/superlogger/LoggingCategory
	at com.zack6849.superlogger.EventListener.onPlayerQuit(EventListener.java:173) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	... 12 more

**Comment by zack6849** [comment] 2015-12-05 23:12
So sorry, this has been fixed here http://dev.bukkit.org/bukkit-plugins/super-logger/files/31-super-logger-v1-7-1/

**Comment by zack6849** [comment] 2015-12-05 23:13
Duplicate of #5

**Closed by zack6849** 2015-12-05 23:12 UTC
